-- Migration: Signup trust & SEO foundations (schema contract v1)
--
-- Purpose:
--   1. Give every streamer a stable, unique, URL-safe `username` so the public
--      profile can live at `/[username]` and appear in sitemap.xml.
--   2. Introduce an explicit trust pipeline (`verification_status`,
--      `is_active`, KYC submissions, payout accounts) so a brand only ever sees
--      streamers Salda has actually vetted.
--   3. Replace free-text `location` with a canonical `city_slug` drawn from the
--      30-city registry in `lib/cities.ts`, which powers `/location/<slug>` SEO
--      pages and shipping logistics.
--
-- Affected objects:
--   - public.streamers                          (new columns + indexes + backfill)
--   - public.users                              (new columns + backfill)
--   - public.streamer_verification_submissions  (new table)
--   - public.streamer_payout_accounts           (new table)
--   - public.is_admin()                         (new helper function)
--   - public.salda_set_updated_at()             (new trigger function)
--   - storage.buckets / storage.objects         (new private bucket + policies)
--
-- Special considerations:
--   - The production database has live rows. Every step below is written to be
--     safely re-runnable and to keep currently-bookable streamers bookable; see
--     the GRANDFATHERING note in section 3.
--   - New tables enable Row Level Security and grant nothing to `anon`: KYC
--     documents and bank accounts must never be readable with the public key.
--   - Admin access mirrors `app/admin/layout.tsx`, which uses an email
--     allowlist; see section 1 for how that allowlist reaches the database.


-- ============================================================================
-- 1) ADMIN IDENTIFICATION
--
-- `app/admin/layout.tsx` has no admin role in the data model (users.user_type
-- is only 'client' | 'streamer'), so it gates /admin on a comma-separated
-- ADMIN_EMAILS environment variable. Postgres cannot read a Next.js env var, so
-- the same allowlist is mirrored into a database setting and compared against
-- the caller's JWT email. Fail-closed, exactly like the app: an unset setting
-- means nobody is an admin.
--
-- SET THIS AFTER APPLYING THE MIGRATION (values must match ADMIN_EMAILS):
--   alter database postgres set app.admin_emails = 'owner@salda.id,ops@salda.id';
--   -- then reconnect, or `select pg_reload_conf();`
--
-- Server code that runs with the service-role key (utils/supabase/admin.ts)
-- bypasses RLS entirely and does not depend on this setting.
-- ============================================================================

-- security definer on purpose: this runs inside RLS policies, so it must not
-- depend on the caller holding privileges on the auth schema. If it raised
-- "permission denied for schema auth" instead of returning false, every policy
-- that calls it would error out and a streamer would lose access to their own
-- rows. It reads no tables and takes no arguments, so there is nothing an
-- attacker can steer.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from
      unnest(
        string_to_array(
          lower(coalesce(current_setting('app.admin_emails', true), '')),
          ','
        )
      ) as allowlist (email)
    where
      btrim(allowlist.email) <> ''
    and
      btrim(allowlist.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

comment on function public.is_admin() is 'True when the caller''s JWT email appears in the app.admin_emails database setting. Database mirror of the ADMIN_EMAILS allowlist enforced by app/admin/layout.tsx. Fail-closed: returns false when the setting is unset.';

grant execute on function public.is_admin() to anon, authenticated, service_role;


-- ============================================================================
-- 2) STREAMERS: NEW COLUMNS
--
-- `username` stays nullable in the database even though signup always writes
-- one: making it NOT NULL would require a table rewrite and would break any
-- in-flight insert issued by the old application build during deploy. The
-- application layer is the enforcement point.
-- ============================================================================

alter table public.streamers
  add column if not exists username text;

comment on column public.streamers.username is 'Public profile slug used for /[username] and sitemap.xml. Unique case-insensitively; generated by lib/username.ts.';

alter table public.streamers
  add column if not exists is_active boolean not null default true;

comment on column public.streamers.is_active is 'Streamer-controlled availability switch. False hides the profile from search and booking without deleting it. Existing rows default to true so nobody disappears when this ships.';

alter table public.streamers
  add column if not exists verified_at timestamptz;

alter table public.streamers
  add column if not exists verified_by uuid references auth.users (id);

alter table public.streamers
  add column if not exists rejection_reason text;

alter table public.streamers
  add column if not exists city_slug text;

comment on column public.streamers.city_slug is 'Canonical city slug from the registry in lib/cities.ts. Drives /location/<slug> SEO pages and shipping logistics. Supersedes the free-text `location` column, which is kept for display and legacy reads.';


-- ============================================================================
-- 3) STREAMERS: VERIFICATION STATUS (+ GRANDFATHERING)
--
-- The column is added and backfilled inside one guarded block so the backfill
-- runs exactly once — on the run that creates the column. Re-running this
-- migration must never reset a streamer an admin has since rejected or
-- suspended back to 'approved'.
-- ============================================================================

do $$
declare
  column_already_existed boolean;
begin
  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'streamers'
      and column_name = 'verification_status'
  )
  into column_already_existed;

  if not column_already_existed then
    alter table public.streamers
      add column verification_status text not null default 'pending';

    /*
      GRANDFATHERING — read this before changing it.

      Every streamer that already exists is marked 'approved' with
      verified_at = now(). This is deliberate: the new default 'pending' must
      apply only to NEW signups, otherwise every currently-bookable streamer
      would vanish the moment this ships.

      verified_by is deliberately left null — no admin actually reviewed these
      rows, and recording a fake reviewer would poison the audit trail.
    */
    update public.streamers
    set verification_status = 'approved',
        verified_at = coalesce(verified_at, now());
  end if;
end;
$$;

comment on column public.streamers.verification_status is 'Trust state of the streamer: pending (new signup, awaiting review), approved (bookable), rejected (failed review), suspended (previously approved, revoked). Rows that predate this column were grandfathered to approved.';

-- The CHECK is added after the backfill so the backfill can never be blocked by
-- a value it is itself about to write.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.streamers'::regclass
      and conname = 'streamers_verification_status_check'
  ) then
    alter table public.streamers
      add constraint streamers_verification_status_check
      check (verification_status in ('pending', 'approved', 'rejected', 'suspended'));
  end if;
end;
$$;


-- ============================================================================
-- 4) STREAMERS: USERNAME BACKFILL
--
-- Two passes, both idempotent, both mirroring the rules in lib/username.ts
-- (lowercase, [a-z0-9_-], must start and end alphanumeric, 3-30 chars, not a
-- reserved route name):
--   4a. Resolve any pre-existing case-insensitive duplicates, which would
--       otherwise make the unique index in section 5 impossible to create.
--   4b. Assign a username to every row that has none.
-- The unique index is created only AFTER both passes have run.
-- ============================================================================

do $$
declare
  -- Mirror of RESERVED_USERNAMES in lib/username.ts. Each of these already
  -- resolves to a real route, so a streamer must never be able to hold one.
  reserved_usernames text[] := array[
    'admin', 'api', 'auth', 'booking-detail', 'client-bookings',
    'forgot-password', 'location', 'locations', 'messages', 'notifications',
    'privacy-notice', 'protected', 'reset-password', 'settings', 'sign-in',
    'sign-up', 'sitemap', 'streamer-dashboard', 'streamer-schedule',
    'streamer-sign-up', 'streamers', 'terms', 'tutorial', 'robots', 'salda',
    'support', 'help', 'about', 'contact', 'me', 'new', 'null', 'undefined'
  ];
  streamer record;
  stem text;
  candidate text;
  attempt integer;
begin
  /*
    4a. Duplicate resolution.

    Only rows that already carry a username are touched, and the lowest id
    keeps its value untouched — it is the oldest, most likely to be linked
    from the outside. Later duplicates are re-suffixed, which does change a
    live URL, but a case-insensitively unique username is a hard requirement
    for /[username] routing and there is no other way to reconcile them.
  */
  for streamer in
    select duplicates.id, duplicates.username
    from (
      select
        streamers.id,
        streamers.username,
        row_number() over (
          partition by lower(streamers.username)
          order by streamers.id
        ) as occurrence
      from public.streamers
      where streamers.username is not null
        and btrim(streamers.username) <> ''
    ) as duplicates
    where duplicates.occurrence > 1
    order by duplicates.id
  loop
    stem := regexp_replace(lower(btrim(streamer.username)), '[_-]+$', '');
    if length(stem) < 3 then
      stem := 'streamer-' || streamer.id::text;
    end if;

    attempt := 1;
    candidate := stem;
    while candidate = any (reserved_usernames)
       or exists (
            select 1
            from public.streamers
            where lower(public.streamers.username) = candidate
              and public.streamers.id <> streamer.id
          )
    loop
      attempt := attempt + 1;
      -- withSuffix() from lib/username.ts: trim the stem so the suffixed
      -- username still fits in 30 characters, then append "-<n>".
      candidate := regexp_replace(
        left(stem, 30 - length('-' || attempt::text)),
        '[_-]+$', ''
      ) || '-' || attempt::text;
    end loop;

    update public.streamers
    set username = candidate
    where public.streamers.id = streamer.id;
  end loop;

  /*
    4b. Assignment for rows with no username.

    The stem is slugifyUsername(first_name + ' ' + last_name) ported to SQL.
    When the name yields fewer than 3 usable characters (empty, emoji-only,
    initials) the row falls back to `streamer-<id>`: unlike lib/username.ts's
    generic "streamer-baru" stem, the id is already unique, so the fallback
    does not force every unnamed row through the collision loop.
  */
  for streamer in
    select
      streamers.id,
      streamers.first_name,
      streamers.last_name
    from public.streamers
    where streamers.username is null
       or btrim(streamers.username) = ''
    order by streamers.id
  loop
    -- Strip accents, then apply the same transformations as slugifyUsername().
    stem := lower(
      translate(
        coalesce(streamer.first_name, '') || ' ' || coalesce(streamer.last_name, ''),
        'áàâäãåéèêëíìîïóòôöõúùûüñçÁÀÂÄÃÅÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÑÇ',
        'aaaaaaeeeeiiiiooooouuuuncAAAAAAEEEEIIIIOOOOOUUUUNC'
      )
    );
    stem := regexp_replace(stem, '[^a-z0-9_-]+', '-', 'g');
    stem := regexp_replace(stem, '-{2,}', '-', 'g');
    stem := regexp_replace(stem, '^[_-]+', '');
    stem := regexp_replace(stem, '[_-]+$', '');
    stem := left(stem, 30);
    stem := regexp_replace(stem, '[_-]+$', '');

    if length(stem) < 3 then
      stem := 'streamer-' || streamer.id::text;
    end if;

    attempt := 1;
    candidate := stem;
    while candidate = any (reserved_usernames)
       or exists (
            select 1
            from public.streamers
            where lower(public.streamers.username) = candidate
          )
    loop
      attempt := attempt + 1;
      candidate := regexp_replace(
        left(stem, 30 - length('-' || attempt::text)),
        '[_-]+$', ''
      ) || '-' || attempt::text;
    end loop;

    update public.streamers
    set username = candidate
    where public.streamers.id = streamer.id;
  end loop;
end;
$$;


-- ============================================================================
-- 5) STREAMERS: USERNAME UNIQUENESS
--
-- Case-insensitive: /Rizky and /rizky must be the same profile, never two.
-- ============================================================================

create unique index if not exists streamers_username_lower_key
  on public.streamers (lower(username));


-- ============================================================================
-- 6) USERS: NEW COLUMNS
--
-- `phone` holds E.164 ("+628…") as produced by lib/phone.ts normalizePhone().
-- It is the WhatsApp contact channel, which is how Indonesian brands and
-- streamers actually reach each other.
-- ============================================================================

alter table public.users
  add column if not exists phone text;

comment on column public.users.phone is 'Contact number in E.164 format (+628…), normalized by lib/phone.ts. Used for WhatsApp contact links.';

alter table public.users
  add column if not exists phone_verified boolean not null default false;

comment on column public.users.phone_verified is 'True once the phone number has completed OTP verification. Existing rows start false: nobody has been verified yet, and claiming otherwise would defeat the check.';

alter table public.users
  add column if not exists city_slug text;

comment on column public.users.city_slug is 'Canonical city slug from lib/cities.ts. Supersedes the free-text `location` column.';


-- ============================================================================
-- 7) CITY BACKFILL
--
-- Translates the alias table in lib/cities.ts into SQL so existing free-text
-- `location` values can be resolved to canonical slugs. The helper is created
-- for this backfill and DROPPED at the end of the section on purpose:
-- lib/cities.ts must stay the single source of truth, and a permanent copy of
-- the alias table in the database would silently drift away from it.
--
-- Matching mirrors resolveCity(): normalize to lowercase, punctuation-free,
-- single-spaced, then look for an exact key. Rows that match nothing keep NULL
-- rather than being guessed at.
-- ============================================================================

create or replace function public.salda_resolve_city_slug(raw text)
returns text
language sql
immutable
as $$
  with normalized as (
    -- normalizeKey() from lib/cities.ts: lowercase, non-alphanumerics collapsed
    -- to single spaces, trimmed. "DKI  Jakarta." -> "dki jakarta".
    select btrim(regexp_replace(lower(coalesce(raw, '')), '[^a-z0-9]+', ' ', 'g')) as key
  ),
  city_keys (key, slug) as (
    values
      -- Each row is a slug, a lowercased display name, or a declared alias,
      -- already written in normalized form.
      ('jakarta', 'jakarta'),
      ('dki jakarta', 'jakarta'),
      ('dki', 'jakarta'),
      ('jkt', 'jakarta'),
      ('jakarta pusat', 'jakarta'),
      ('jakarta selatan', 'jakarta'),
      ('jakarta barat', 'jakarta'),
      ('jakarta timur', 'jakarta'),
      ('jakarta utara', 'jakarta'),
      ('jakpus', 'jakarta'),
      ('jaksel', 'jakarta'),
      ('jakbar', 'jakarta'),
      ('jaktim', 'jakarta'),
      ('jakut', 'jakarta'),
      ('surabaya', 'surabaya'),
      ('sby', 'surabaya'),
      ('kota surabaya', 'surabaya'),
      ('bandung', 'bandung'),
      ('bdg', 'bandung'),
      ('kota bandung', 'bandung'),
      ('medan', 'medan'),
      ('mdn', 'medan'),
      ('kota medan', 'medan'),
      ('semarang', 'semarang'),
      ('smg', 'semarang'),
      ('kota semarang', 'semarang'),
      ('yogyakarta', 'yogyakarta'),
      ('jogja', 'yogyakarta'),
      ('yogya', 'yogyakarta'),
      ('jogjakarta', 'yogyakarta'),
      ('diy', 'yogyakarta'),
      ('yk', 'yogyakarta'),
      ('makassar', 'makassar'),
      ('ujung pandang', 'makassar'),
      ('mks', 'makassar'),
      ('denpasar', 'denpasar'),
      ('bali', 'denpasar'),
      ('dps', 'denpasar'),
      ('palembang', 'palembang'),
      ('plg', 'palembang'),
      ('tangerang', 'tangerang'),
      ('tangerang selatan', 'tangerang'),
      ('tangsel', 'tangerang'),
      ('kota tangerang', 'tangerang'),
      ('bekasi', 'bekasi'),
      ('kota bekasi', 'bekasi'),
      ('depok', 'depok'),
      ('kota depok', 'depok'),
      ('malang', 'malang'),
      ('kota malang', 'malang'),
      ('mlg', 'malang'),
      ('bogor', 'bogor'),
      ('kota bogor', 'bogor'),
      ('batam', 'batam'),
      ('kota batam', 'batam'),
      ('pekanbaru', 'pekanbaru'),
      ('pku', 'pekanbaru'),
      ('bandar lampung', 'bandar-lampung'),
      ('bandarlampung', 'bandar-lampung'),
      ('lampung', 'bandar-lampung'),
      ('tanjungkarang', 'bandar-lampung'),
      ('padang', 'padang'),
      ('kota padang', 'padang'),
      ('manado', 'manado'),
      ('mdo', 'manado'),
      ('samarinda', 'samarinda'),
      ('smd', 'samarinda'),
      ('banjarmasin', 'banjarmasin'),
      ('bjm', 'banjarmasin'),
      ('balikpapan', 'balikpapan'),
      ('bpp', 'balikpapan'),
      ('pontianak', 'pontianak'),
      ('ptk', 'pontianak'),
      ('serang', 'serang'),
      ('kota serang', 'serang'),
      ('cirebon', 'cirebon'),
      ('kota cirebon', 'cirebon'),
      ('sukabumi', 'sukabumi'),
      ('kota sukabumi', 'sukabumi'),
      ('jambi', 'jambi'),
      ('kota jambi', 'jambi'),
      ('ambon', 'ambon'),
      ('kota ambon', 'ambon'),
      ('jayapura', 'jayapura'),
      ('kota jayapura', 'jayapura'),
      ('mataram', 'mataram'),
      ('lombok', 'mataram'),
      ('ntb', 'mataram')
  )
  select coalesce(
    -- Exact match on the whole normalized string.
    (
      select city_keys.slug
      from city_keys, normalized
      where city_keys.key = normalized.key
      limit 1
    ),
    -- Fallback for legacy free text such as "Bandung, Jawa Barat": look for a
    -- key appearing as a whole word. Keys shorter than 5 characters are skipped
    -- because abbreviations like "dki" or "yk" are too easy to hit by accident.
    -- The longest match wins, so "bandar lampung" beats "lampung".
    (
      select city_keys.slug
      from city_keys, normalized
      where length(city_keys.key) >= 5
        and normalized.key <> ''
        and ' ' || normalized.key || ' ' like '% ' || city_keys.key || ' %'
      order by length(city_keys.key) desc, city_keys.slug
      limit 1
    )
  );
$$;

comment on function public.salda_resolve_city_slug(text) is 'Temporary backfill helper: resolves legacy free-text locations to a canonical city slug. Dropped at the end of this migration — lib/cities.ts is the single source of truth.';

-- Best-effort only: `where city_slug is null` means an explicit choice made by
-- a streamer or admin is never overwritten, including on a re-run.
update public.streamers
set city_slug = public.salda_resolve_city_slug(location)
where city_slug is null
  and location is not null
  and public.salda_resolve_city_slug(location) is not null;

update public.users
set city_slug = public.salda_resolve_city_slug(location)
where city_slug is null
  and location is not null
  and public.salda_resolve_city_slug(location) is not null;

-- Drops the helper so the alias table exists in exactly one place (lib/cities.ts).
-- Nothing else references it: it was created a few statements ago purely for
-- the two backfills above.
drop function if exists public.salda_resolve_city_slug(text);


-- ============================================================================
-- 8) STREAMERS: INDEXES
--
-- The public listing and the admin queue both filter on these columns.
-- ============================================================================

create index if not exists idx_streamers_verification_status
  on public.streamers (verification_status);

create index if not exists idx_streamers_city_slug
  on public.streamers (city_slug);


-- ============================================================================
-- 9) SHARED updated_at TRIGGER
-- ============================================================================

create or replace function public.salda_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.salda_set_updated_at() is 'Trigger function that stamps updated_at on every UPDATE, so the column cannot drift when a writer forgets to set it.';


-- ============================================================================
-- 10) STREAMER VERIFICATION SUBMISSIONS
--
-- One row per KYC attempt by a streamer. Kept separate from public.streamers so
-- the sensitive documents live behind their own RLS boundary and a rejected
-- attempt stays on the record instead of being overwritten.
-- ============================================================================

create table if not exists public.streamer_verification_submissions (
  id uuid primary key default gen_random_uuid(),
  streamer_id bigint not null references public.streamers (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  id_card_url text,
  selfie_url text,
  platform_proof_url text,
  platform_handle text,
  status text not null default 'pending',
  notes text,
  reviewed_by uuid references auth.users (id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.streamer_verification_submissions is 'KYC submissions from streamers: identity documents, a selfie, and proof of their TikTok/Shopee Live account. An admin reviews each row and mirrors the outcome onto streamers.verification_status.';
comment on column public.streamer_verification_submissions.id_card_url is 'Storage path inside the private verification_documents bucket, always prefixed with the owning user_id.';
comment on column public.streamer_verification_submissions.status is 'pending (awaiting review), approved, or rejected. Only admins may move it off pending.';
comment on column public.streamer_verification_submissions.notes is 'Reviewer notes. Doubles as the rejection explanation shown back to the streamer.';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.streamer_verification_submissions'::regclass
      and conname = 'streamer_verification_submissions_status_check'
  ) then
    alter table public.streamer_verification_submissions
      add constraint streamer_verification_submissions_status_check
      check (status in ('pending', 'approved', 'rejected'));
  end if;
end;
$$;

create index if not exists idx_streamer_verification_submissions_status
  on public.streamer_verification_submissions (status);

create index if not exists idx_streamer_verification_submissions_streamer
  on public.streamer_verification_submissions (streamer_id);

drop trigger if exists set_updated_at on public.streamer_verification_submissions;
create trigger set_updated_at
  before update on public.streamer_verification_submissions
  for each row
  execute function public.salda_set_updated_at();

alter table public.streamer_verification_submissions enable row level security;

-- No policy is granted to `anon`. Identity documents must be unreachable with
-- the public browser key, and an absent policy denies by default.

drop policy if exists "verification_submissions_select_own" on public.streamer_verification_submissions;
create policy "verification_submissions_select_own"
  on public.streamer_verification_submissions
  for select
  to authenticated
  using (
    streamer_id in (select id from public.streamers where user_id = auth.uid())
  );

drop policy if exists "verification_submissions_select_admin" on public.streamer_verification_submissions;
create policy "verification_submissions_select_admin"
  on public.streamer_verification_submissions
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "verification_submissions_insert_own" on public.streamer_verification_submissions;
create policy "verification_submissions_insert_own"
  on public.streamer_verification_submissions
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and streamer_id in (select id from public.streamers where user_id = auth.uid())
    and status = 'pending'
  );

drop policy if exists "verification_submissions_update_own_pending" on public.streamer_verification_submissions;
create policy "verification_submissions_update_own_pending"
  on public.streamer_verification_submissions
  for update
  to authenticated
  using (
    status = 'pending'
    and streamer_id in (select id from public.streamers where user_id = auth.uid())
  )
  with check (
    status = 'pending'
    and streamer_id in (select id from public.streamers where user_id = auth.uid())
  );

drop policy if exists "verification_submissions_update_admin" on public.streamer_verification_submissions;
create policy "verification_submissions_update_admin"
  on public.streamer_verification_submissions
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

comment on policy "verification_submissions_select_own" on public.streamer_verification_submissions is 'A streamer can see the submissions attached to their own streamer profile, so the dashboard can show review progress and the rejection reason.';
comment on policy "verification_submissions_select_admin" on public.streamer_verification_submissions is 'Admins on the ADMIN_EMAILS allowlist read every submission — without this the review queue in /admin would be empty.';
comment on policy "verification_submissions_insert_own" on public.streamer_verification_submissions is 'A streamer may only submit for their own profile, as themselves, and only as pending: this is the write path for the KYC form.';
comment on policy "verification_submissions_update_own_pending" on public.streamer_verification_submissions is 'A streamer may correct a submission only while it is still pending, and the status must remain pending on both sides of the update. This is what stops a streamer from self-approving by writing status = approved.';
comment on policy "verification_submissions_update_admin" on public.streamer_verification_submissions is 'Only admins can move a submission to approved or rejected and record who reviewed it.';

-- Deliberately no DELETE policy: submissions are the audit trail for a trust
-- decision and must not be erasable by the streamer being reviewed.


-- ============================================================================
-- 11) STREAMER PAYOUT ACCOUNTS
--
-- Where Salda sends a streamer's earnings. Separate table because a streamer
-- may rotate accounts over time and the history matters for reconciliation.
-- ============================================================================

create table if not exists public.streamer_payout_accounts (
  id uuid primary key default gen_random_uuid(),
  streamer_id bigint not null references public.streamers (id) on delete cascade,
  bank_code text not null,
  bank_name text not null,
  account_number text not null,
  account_holder_name text not null,
  is_primary boolean not null default true,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.streamer_payout_accounts is 'Bank accounts a streamer can be paid out to. At most one row per streamer may be primary; that is the account used for automatic disbursement.';
comment on column public.streamer_payout_accounts.bank_code is 'Bank identifier used by the disbursement provider (e.g. bca, mandiri, bni, bri).';
comment on column public.streamer_payout_accounts.verified_at is 'Set when the account holder name has been confirmed against the bank. Should only be written server-side, after a name check.';

create index if not exists idx_streamer_payout_accounts_streamer
  on public.streamer_payout_accounts (streamer_id);

-- Partial unique index: a streamer may keep several accounts on file but only
-- one of them can be flagged primary, so payouts always have one destination.
create unique index if not exists idx_streamer_payout_accounts_one_primary
  on public.streamer_payout_accounts (streamer_id)
  where is_primary;

drop trigger if exists set_updated_at on public.streamer_payout_accounts;
create trigger set_updated_at
  before update on public.streamer_payout_accounts
  for each row
  execute function public.salda_set_updated_at();

alter table public.streamer_payout_accounts enable row level security;

-- As above, `anon` gets no policy at all: bank details must never be readable
-- with the public browser key.

drop policy if exists "payout_accounts_select_own" on public.streamer_payout_accounts;
create policy "payout_accounts_select_own"
  on public.streamer_payout_accounts
  for select
  to authenticated
  using (
    streamer_id in (select id from public.streamers where user_id = auth.uid())
  );

drop policy if exists "payout_accounts_select_admin" on public.streamer_payout_accounts;
create policy "payout_accounts_select_admin"
  on public.streamer_payout_accounts
  for select
  to authenticated
  using (public.is_admin());

drop policy if exists "payout_accounts_insert_own" on public.streamer_payout_accounts;
create policy "payout_accounts_insert_own"
  on public.streamer_payout_accounts
  for insert
  to authenticated
  with check (
    streamer_id in (select id from public.streamers where user_id = auth.uid())
  );

drop policy if exists "payout_accounts_update_own" on public.streamer_payout_accounts;
create policy "payout_accounts_update_own"
  on public.streamer_payout_accounts
  for update
  to authenticated
  using (
    streamer_id in (select id from public.streamers where user_id = auth.uid())
  )
  with check (
    streamer_id in (select id from public.streamers where user_id = auth.uid())
  );

drop policy if exists "payout_accounts_update_admin" on public.streamer_payout_accounts;
create policy "payout_accounts_update_admin"
  on public.streamer_payout_accounts
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "payout_accounts_delete_own" on public.streamer_payout_accounts;
create policy "payout_accounts_delete_own"
  on public.streamer_payout_accounts
  for delete
  to authenticated
  using (
    streamer_id in (select id from public.streamers where user_id = auth.uid())
  );

comment on policy "payout_accounts_select_own" on public.streamer_payout_accounts is 'A streamer sees only the bank accounts attached to their own profile.';
comment on policy "payout_accounts_select_admin" on public.streamer_payout_accounts is 'Admins read every payout account, which is required to reconcile and release disbursements.';
comment on policy "payout_accounts_insert_own" on public.streamer_payout_accounts is 'A streamer can add a bank account only to their own profile, never to someone else''s — this is the rule that stops earnings being redirected.';
comment on policy "payout_accounts_update_own" on public.streamer_payout_accounts is 'A streamer can correct their own bank details. verified_at is expected to be (re)set server-side after a name check; this policy does not itself protect it.';
comment on policy "payout_accounts_update_admin" on public.streamer_payout_accounts is 'Admins can mark an account verified or fix a bad record during support.';
comment on policy "payout_accounts_delete_own" on public.streamer_payout_accounts is 'A streamer can remove a bank account they no longer use. Unlike verification submissions, an unused payout account carries no audit value.';


-- ============================================================================
-- 12) VERIFICATION DOCUMENTS STORAGE BUCKET
--
-- PRIVATE bucket (public = false) — unlike the existing `streamers` and
-- `brand-guidelines` buckets, these objects are identity documents and must
-- only ever be reachable through a signed URL.
--
-- PATH CONVENTION (enforced by the policies below):
--   verification_documents/<auth.uid()>/<filename>
-- The first path segment must be the uploader's user id; anything else is
-- rejected on insert and invisible on read.
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'verification_documents',
  'verification_documents',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "verification_documents_insert_own_prefix" on storage.objects;
create policy "verification_documents_insert_own_prefix"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'verification_documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "verification_documents_select_own_prefix" on storage.objects;
create policy "verification_documents_select_own_prefix"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'verification_documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "verification_documents_update_own_prefix" on storage.objects;
create policy "verification_documents_update_own_prefix"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'verification_documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'verification_documents'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "verification_documents_select_admin" on storage.objects;
create policy "verification_documents_select_admin"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'verification_documents'
    and public.is_admin()
  );

comment on policy "verification_documents_insert_own_prefix" on storage.objects is 'A streamer may upload verification documents only under a folder named after their own user id, which is what keeps one streamer''s KYC files out of another''s namespace.';
comment on policy "verification_documents_select_own_prefix" on storage.objects is 'A streamer may read back only the documents they uploaded, so they can review what they submitted.';
comment on policy "verification_documents_update_own_prefix" on storage.objects is 'Allows re-uploading to the same path when a streamer replaces a blurry document; still confined to their own prefix.';
comment on policy "verification_documents_select_admin" on storage.objects is 'Admins on the ADMIN_EMAILS allowlist read every verification document — the review itself is impossible otherwise.';

-- Deliberately no DELETE policy on this bucket: a submitted identity document
-- is part of the audit trail for an approval decision. Removal is an admin
-- action, performed with the service-role key.
